## Map of all accepted tags to a unifying mood ## 

tag_map = {
    "Angry": ["angry", "aggressive", "agressive", "frustration"],
    "Beach": ["beach", "beachmusic", "beachy", "island", "jamaica", "summer", "summerly", "sunny"],
    "Chill": ["chill", "lounge", "lounging", "calm", "chillhouse", "easy", "easylistening", "relaxing", "cool", "cooljazz"],
    "Dance": ["dance", "clubbing", "clubdance", "clubhouse", "clubing", "danceable", "danse", "funkyhouse", "funkydiscohouse"],
    "Dark": ["dark", "electrodark", "horror", "sinister"], 
    "Dreamy": ["dreamy", "delirium", "dream", "dreamdrance", "dreams"],
    "Elegant": ["elegant", "cocktail"], 
    "Emotional": ["emotional", "emotionnal", "emotions"],
    "Ethereal": ["ethereal" "scifi", "space", "atmospheric"], 
    "Funky": ["funky", "discofunk", "funkfusion", "funkrock", "funkybass", "funkydiscohouse", "funkyhouse"],
    "Groovy": ["groovy", "grooves", "groovey", "groovysong"],
    "Happy": ["happy", "celebration", "cheerful", "delirium", "euphoric", "feelgood", "fun", "goodvibes", "happyness", "vibes"],
    "Hype": ["hype", "bop", "drop", "exciting", "uplift", "motivated", "aye"],
    "Love": ["love", "heart", "kiss", "romantic", "romantics", "romantique"], 
    "Motivational": ["motivational", "inspirational", "motivated", "uplift", "uplifting"],
    "Nostalgic": ["nostalgic", "nostalgia", "nostalgie"],
    "Party": ["party", "beer", "celebration", "alcohol", "alcohal", "pub", "party"],
    "Peaceful": ["peaceful", "peace", "ambientchill", "ambiante", "serene", "sleep"],
    "Powerful": ["powerful", "power", "intense"],
    "Sad": ["sad", "breakup", "heartbreak", "lonely", "lonelyness", "longing", "sentimental", "solemn", "sorrow", "teardrops", "melancholic"],
    "Sexy": ["sexy", "intimate", "romantic"],
    "Slow": ["slow", "slowmotion", "slowtempo"],
    "Soft": ["soft", "tender"],
    "Trippy": ["trippy", "psychadelic"],
    "Upbeat": ["upbeat", "energetic", "fast", "uptempo"],
    "Weird": ["weird", "quirky", "strange"],
}