tag_map = {
    "Angry": ["aggressive", "agressive", "frustration"],
    "Beach": ["beachmusic", "beachy", "island", "jamaica", "summer", "summerly", "sunny"],
    "Chill": ["lounge", "lounging", "calm", "chillhouse", "easy", "easylistening", "relaxing", "cool", "cooljazz"],
    "Dance": ["clubbing", "clubdance", "clubhouse", "clubing", "danceable", "danse", "funkyhouse", "funkydiscohouse"],
    "Dark": ["electrodark", "horror", "sinister"], 
    "Dreamy": ["delirium", "dream", "dreamdrance", "dreams"],
    "Elegant": ["cocktail"], 
    "Emotional": ["emotionnal", "emotions"],
    "Ethereal": ["scifi", "space", "atmospheric"], 
    "Funky": ["discofunk", "funkfusion", "funkrock", "funkybass", "funkydiscohouse", "funkyhouse"],
    "Groovy": ["grooves", "groovey", "groovysong"],
    "Happy": ["celebration", "cheerful", "delirium", "euphoric", "feelgood", "fun", "goodvibes", "happyness", "vibes"],
    "Hype": ["bop", "drop", "exciting", "uplift", "motivated", "aye"],
    "Love": ["heart", "kiss", "romantic", "romantics", "romantique"], 
    "Motivational": ["inspirational", "motivated", "uplift", "uplifting"],
    "Nostalgic": ["nostalgia", "nostalgie"],
    "Party": ["beer", "celebration", "alcohol", "alcohal", "pub", "party"],
    "Peaceful": ["peace", "ambientchill", "ambiante", "serene", "sleep"],
    "Powerful": ["power", "intense"],
    "Sad": ["breakup", "heartbreak", "lonely", "lonelyness", "longing", "sentimental", "solemn", "sorrow", "teardrops", "melancholic"],
    "Sexy": ["intimate", "romantic"],
    "Slow": ["slowmotion", "slowtempo"],
    "Soft": ["tender"],
    "Trippy": ["psychadelic"],
    "Upbeat": ["energetic", "fast", "uptempo"],
    "Weird": ["quirky", "strange"],
}